
-- Add many more products to the database
INSERT INTO products (name, category, image_url) VALUES
-- Fruits
('Limoni', 'Frutta', 'https://placehold.co/100x100?text=Limoni'),
('Pompelmo', 'Frutta', 'https://placehold.co/100x100?text=Pompelmo'),
('Mango', 'Frutta', 'https://placehold.co/100x100?text=Mango'),
('Papaya', 'Frutta', 'https://placehold.co/100x100?text=Papaya'),
('Avocado', 'Frutta', 'https://placehold.co/100x100?text=Avocado'),
('Ciliegie', 'Frutta', 'https://placehold.co/100x100?text=Ciliegie'),
('Albicocche', 'Frutta', 'https://placehold.co/100x100?text=Albicocche'),
('Prugne', 'Frutta', 'https://placehold.co/100x100?text=Prugne'),
('Nespole', 'Frutta', 'https://placehold.co/100x100?text=Nespole'),
('Fichi', 'Frutta', 'https://placehold.co/100x100?text=Fichi'),
('Melograno', 'Frutta', 'https://placehold.co/100x100?text=Melograno'),
('Cocco', 'Frutta', 'https://placehold.co/100x100?text=Cocco'),
('Passion Fruit', 'Frutta', 'https://placehold.co/100x100?text=Passion+Fruit'),
('Litchi', 'Frutta', 'https://placehold.co/100x100?text=Litchi'),

-- Vegetables
('Broccoli', 'Verdura', 'https://placehold.co/100x100?text=Broccoli'),
('Cavolfiore', 'Verdura', 'https://placehold.co/100x100?text=Cavolfiore'),
('Cavolo cappuccio', 'Verdura', 'https://placehold.co/100x100?text=Cavolo'),
('Spinaci', 'Verdura', 'https://placehold.co/100x100?text=Spinaci'),
('Rucola', 'Verdura', 'https://placehold.co/100x100?text=Rucola'),
('Lattuga romana', 'Verdura', 'https://placehold.co/100x100?text=Lattuga+Romana'),
('Radicchio', 'Verdura', 'https://placehold.co/100x100?text=Radicchio'),
('Sedano', 'Verdura', 'https://placehold.co/100x100?text=Sedano'),
('Finocchio', 'Verdura', 'https://placehold.co/100x100?text=Finocchio'),
('Asparagi', 'Verdura', 'https://placehold.co/100x100?text=Asparagi'),
('Carciofi', 'Verdura', 'https://placehold.co/100x100?text=Carciofi'),
('Barbabietola', 'Verdura', 'https://placehold.co/100x100?text=Barbabietola'),
('Rape rosse', 'Verdura', 'https://placehold.co/100x100?text=Rape+Rosse'),
('Porro', 'Verdura', 'https://placehold.co/100x100?text=Porro'),
('Cetrioli', 'Verdura', 'https://placehold.co/100x100?text=Cetrioli'),
('Fagiolini', 'Verdura', 'https://placehold.co/100x100?text=Fagiolini'),
('Piselli', 'Verdura', 'https://placehold.co/100x100?text=Piselli'),
('Fave', 'Verdura', 'https://placehold.co/100x100?text=Fave'),

-- Meat and Fish
('Bistecca di manzo', 'Carne', 'https://placehold.co/100x100?text=Bistecca'),
('Costoletta di maiale', 'Carne', 'https://placehold.co/100x100?text=Costoletta'),
('Agnello', 'Carne', 'https://placehold.co/100x100?text=Agnello'),
('Anatra', 'Carne', 'https://placehold.co/100x100?text=Anatra'),
('Coniglio', 'Carne', 'https://placehold.co/100x100?text=Coniglio'),
('Salsiccia', 'Carne', 'https://placehold.co/100x100?text=Salsiccia'),
('Speck', 'Salumi', 'https://placehold.co/100x100?text=Speck'),
('Pancetta', 'Salumi', 'https://placehold.co/100x100?text=Pancetta'),
('Coppa', 'Salumi', 'https://placehold.co/100x100?text=Coppa'),
('Lonza', 'Salumi', 'https://placehold.co/100x100?text=Lonza'),
('Branzino', 'Pesce', 'https://placehold.co/100x100?text=Branzino'),
('Sogliola', 'Pesce', 'https://placehold.co/100x100?text=Sogliola'),
('Trota', 'Pesce', 'https://placehold.co/100x100?text=Trota'),
('Baccalà', 'Pesce', 'https://placehold.co/100x100?text=Baccalà'),
('Sardine', 'Pesce', 'https://placehold.co/100x100?text=Sardine'),
('Alici', 'Pesce', 'https://placehold.co/100x100?text=Alici'),
('Polpo', 'Pesce', 'https://placehold.co/100x100?text=Polpo'),
('Seppie', 'Pesce', 'https://placehold.co/100x100?text=Seppie'),
('Cozze', 'Pesce', 'https://placehold.co/100x100?text=Cozze'),
('Vongole', 'Pesce', 'https://placehold.co/100x100?text=Vongole'),

-- Dairy and Cheese
('Pecorino', 'Latticini', 'https://placehold.co/100x100?text=Pecorino'),
('Taleggio', 'Latticini', 'https://placehold.co/100x100?text=Taleggio'),
('Fontina', 'Latticini', 'https://placehold.co/100x100?text=Fontina'),
('Asiago', 'Latticini', 'https://placehold.co/100x100?text=Asiago'),
('Provolone', 'Latticini', 'https://placehold.co/100x100?text=Provolone'),
('Scamorza', 'Latticini', 'https://placehold.co/100x100?text=Scamorza'),
('Burrata', 'Latticini', 'https://placehold.co/100x100?text=Burrata'),
('Stracciatella', 'Latticini', 'https://placehold.co/100x100?text=Stracciatella'),
('Fior di latte', 'Latticini', 'https://placehold.co/100x100?text=Fior+di+Latte'),
('Latte di capra', 'Latte', 'https://placehold.co/100x100?text=Latte+Capra'),
('Latte di avena', 'Latte', 'https://placehold.co/100x100?text=Latte+Avena'),
('Latte di riso', 'Latte', 'https://placehold.co/100x100?text=Latte+Riso'),
('Latte di cocco', 'Latte', 'https://placehold.co/100x100?text=Latte+Cocco'),

-- Pasta and Grains
('Tagliatelle', 'Pasta', 'https://placehold.co/100x100?text=Tagliatelle'),
('Rigatoni', 'Pasta', 'https://placehold.co/100x100?text=Rigatoni'),
('Orecchiette', 'Pasta', 'https://placehold.co/100x100?text=Orecchiette'),
('Tortellini', 'Pasta', 'https://placehold.co/100x100?text=Tortellini'),
('Ravioli', 'Pasta', 'https://placehold.co/100x100?text=Ravioli'),
('Gnocchi', 'Pasta', 'https://placehold.co/100x100?text=Gnocchi'),
('Lasagne', 'Pasta', 'https://placehold.co/100x100?text=Lasagne'),
('Riso Arborio', 'Cereali', 'https://placehold.co/100x100?text=Riso+Arborio'),
('Riso Basmati', 'Cereali', 'https://placehold.co/100x100?text=Riso+Basmati'),
('Quinoa', 'Cereali', 'https://placehold.co/100x100?text=Quinoa'),
('Orzo perlato', 'Cereali', 'https://placehold.co/100x100?text=Orzo'),
('Farro', 'Cereali', 'https://placehold.co/100x100?text=Farro'),
('Miglio', 'Cereali', 'https://placehold.co/100x100?text=Miglio'),

-- Beverages
('Prosecco', 'Bevande', 'https://placehold.co/100x100?text=Prosecco'),
('Chianti', 'Bevande', 'https://placehold.co/100x100?text=Chianti'),
('Pinot Grigio', 'Bevande', 'https://placehold.co/100x100?text=Pinot+Grigio'),
('Lambrusco', 'Bevande', 'https://placehold.co/100x100?text=Lambrusco'),
('Aperol', 'Bevande', 'https://placehold.co/100x100?text=Aperol'),
('Limoncello', 'Bevande', 'https://placehold.co/100x100?text=Limoncello'),
('Grappa', 'Bevande', 'https://placehold.co/100x100?text=Grappa'),
('Espresso', 'Bevande', 'https://placehold.co/100x100?text=Espresso'),
('Cappuccino', 'Bevande', 'https://placehold.co/100x100?text=Cappuccino'),
('Tisana', 'Bevande', 'https://placehold.co/100x100?text=Tisana'),
('Camomilla', 'Bevande', 'https://placehold.co/100x100?text=Camomilla'),

-- Condiments and Spices
('Olio extravergine', 'Condimenti', 'https://placehold.co/100x100?text=Olio+EVO'),
('Aceto balsamico', 'Condimenti', 'https://placehold.co/100x100?text=Aceto+Balsamico'),
('Sale marino', 'Condimenti', 'https://placehold.co/100x100?text=Sale+Marino'),
('Pepe nero', 'Condimenti', 'https://placehold.co/100x100?text=Pepe+Nero'),
('Origano', 'Condimenti', 'https://placehold.co/100x100?text=Origano'),
('Basilico', 'Condimenti', 'https://placehold.co/100x100?text=Basilico'),
('Rosmarino', 'Condimenti', 'https://placehold.co/100x100?text=Rosmarino'),
('Salvia', 'Condimenti', 'https://placehold.co/100x100?text=Salvia'),
('Timo', 'Condimenti', 'https://placehold.co/100x100?text=Timo'),
('Prezzemolo', 'Condimenti', 'https://placehold.co/100x100?text=Prezzemolo'),
('Aglio in polvere', 'Condimenti', 'https://placehold.co/100x100?text=Aglio+Polvere'),
('Paprika', 'Condimenti', 'https://placehold.co/100x100?text=Paprika'),
('Curcuma', 'Condimenti', 'https://placehold.co/100x100?text=Curcuma'),
('Zenzero', 'Condimenti', 'https://placehold.co/100x100?text=Zenzero'),

-- Snacks and Sweets
('Patatine', 'Snack', 'https://placehold.co/100x100?text=Patatine'),
('Crackers', 'Snack', 'https://placehold.co/100x100?text=Crackers'),
('Taralli', 'Snack', 'https://placehold.co/100x100?text=Taralli'),
('Grissini', 'Snack', 'https://placehold.co/100x100?text=Grissini'),
('Noci', 'Frutta secca', 'https://placehold.co/100x100?text=Noci'),
('Mandorle', 'Frutta secca', 'https://placehold.co/100x100?text=Mandorle'),
('Pistacchi', 'Frutta secca', 'https://placehold.co/100x100?text=Pistacchi'),
('Nocciole', 'Frutta secca', 'https://placehold.co/100x100?text=Nocciole'),
('Pinoli', 'Frutta secca', 'https://placehold.co/100x100?text=Pinoli'),
('Cioccolato fondente', 'Dolci', 'https://placehold.co/100x100?text=Cioccolato'),
('Miele', 'Dolci', 'https://placehold.co/100x100?text=Miele'),
('Zucchero di canna', 'Dolci', 'https://placehold.co/100x100?text=Zucchero'),
('Cannella', 'Dolci', 'https://placehold.co/100x100?text=Cannella'),
('Vaniglia', 'Dolci', 'https://placehold.co/100x100?text=Vaniglia'),

-- Canned Goods
('Pomodori pelati', 'Conserve', 'https://placehold.co/100x100?text=Pomodori+Pelati'),
('Passata di pomodoro', 'Conserve', 'https://placehold.co/100x100?text=Passata'),
('Fagioli cannellini', 'Conserve', 'https://placehold.co/100x100?text=Fagioli'),
('Ceci', 'Conserve', 'https://placehold.co/100x100?text=Ceci'),
('Lenticchie', 'Conserve', 'https://placehold.co/100x100?text=Lenticchie'),
('Mais', 'Conserve', 'https://placehold.co/100x100?text=Mais'),
('Olive verdi', 'Conserve', 'https://placehold.co/100x100?text=Olive+Verdi'),
('Olive nere', 'Conserve', 'https://placehold.co/100x100?text=Olive+Nere'),
('Capperi', 'Conserve', 'https://placehold.co/100x100?text=Capperi'),
('Acciughe', 'Conserve', 'https://placehold.co/100x100?text=Acciughe'),

-- Baby and Personal Care
('Pannolini', 'Baby Care', 'https://placehold.co/100x100?text=Pannolini'),
('Salviette', 'Baby Care', 'https://placehold.co/100x100?text=Salviette'),
('Shampoo', 'Cura persona', 'https://placehold.co/100x100?text=Shampoo'),
('Balsamo', 'Cura persona', 'https://placehold.co/100x100?text=Balsamo'),
('Dentifricio', 'Cura persona', 'https://placehold.co/100x100?text=Dentifricio'),
('Spazzolino', 'Cura persona', 'https://placehold.co/100x100?text=Spazzolino'),
('Bagnoschiuma', 'Cura persona', 'https://placehold.co/100x100?text=Bagnoschiuma'),
('Crema viso', 'Cura persona', 'https://placehold.co/100x100?text=Crema+Viso'),
('Crema corpo', 'Cura persona', 'https://placehold.co/100x100?text=Crema+Corpo'),
('Deodorante', 'Cura persona', 'https://placehold.co/100x100?text=Deodorante');
