// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijwpwancwwmmwehjlnim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqd3B3YW5jd3dtbXdlaGpsbmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODYwNzQsImV4cCI6MjA2MDc2MjA3NH0.MbZ-3_1eB2xrvC8V1Kpcv1rbB0_519adD0c7fdO0NY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);